### ISSUE TITLE
Migrate clinvar buckets to single region

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#8]
Ticket on [Jira](https://broadworkbench.atlassian.net/browse/DI-304)

**Comment by toneillbroad** [comment]
Ran into the following issue upon first run of the scripts from Audax:
toneill@cloudshell:~ (broad-dsp-monster-clingen-dev)$ python ./role_utility.py create --project_id broad-dsp-monster-clingen-dev
Traceback (most recent call last):
  File "/home/toneill/./role_utility.py", line 165, in <module>
    main()
  File "/home/toneill/./role_utility.py", line 35, in main
    create(args.project_id)
  File "/home/toneill/./role_utility.py", line 43, in create
    enable_api(project_id)
  File "/home/toneill/./role_utility.py", line 123, in enable_api
    cloud_resource_manager_api_status = get_service_api_status(
  File "/home/toneill/./role_utility.py", line 149, in get_service_api_status
    client.services()
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://serviceusage.googleapis.com/v1/projects/broad-dsp-monster-clingen-dev/services/cloudresourcemanager.googleapis.com?alt=json returned "Caller does not have required permission to use project broad-dsp-monster-clingen-dev. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=broad-dsp-monster-clingen-dev and then retry. Propagation of the new permission may take a few minutes.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console IAM admin', 'url': 'https://console.developers.google.com/iam-admin/iam/project?project=broad-dsp-monster-clingen-dev'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'USER_PROJECT_DENIED', 'domain': 'googleapis.com', 'metadata': {'service': 'serviceusage.googleapis.com', 'consumer': 'projects/broad-dsp-monster-clingen-dev'}}]">
